# Generated by Django 3.1.3 on 2021-01-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='zip_number',
        ),
    ]
