# Generated by Django 3.1.3 on 2020-11-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(choices=[('HP', 'HP'), ('Acer', 'Acer'), ('Dell', 'Dell'), ('Sony', 'Sony'), ('Apple', 'Apple'), ('Lenovo', 'Lenovo'), ('Techno', 'Techno'), ('Infinix', 'Infinix'), ('Samsung', 'Samsung'), ('Microsoft', 'Microsoft')], default='Apple', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Laptops', 'Laptops'), ('Tablets', 'Tablets'), ('Phones', 'Phones')], default='Laptops', max_length=150),
        ),
    ]
