# Generated by Django 3.1.3 on 2020-11-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201120_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='product',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
